General:
  oc_implementation: 'hinge'
  gravnet:
    - n: 128
    - n: 128
  n_cluster_space_coordinates: 8
  n_gravnet_space_coordinates: 5

DenseOptions:
  activation: "elu"
  kernel_regularizer_rate: 0.001
  dropout: 0.000001

BatchNormOptions:
  fluidity_decay: 0.1 # go fast to 0.5
  max_viscosity: 0.5
  learn: False

LossOptions:
  energy_loss_weight: .00
  q_min: 2.0
  use_average_cc_pos: 0.99999
  classification_loss_weight: 0.0
  too_much_beta_scale: 0.0
  position_loss_weight: 0.0
  timing_loss_weight: 0.0
  beta_loss_scale: 1.0


Training:
  - stage_1:
    batch_size: 150000
    learning_rate: 0.001
    epochs: 4

  - stage_2:
    batch_size: 180000
    learning_rate: 0.0001
    epochs: 10

  - stage_3:
    batch_size: 180000
    learning_rate: 0.00001
    epochs: 20

